// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using User.Infrastructure.Contexts;

#nullable disable

namespace User.Infrastructure.Migrations
{
    [DbContext(typeof(UserWriteDbContext))]
    [Migration("20241016173058_AchievmentsTest_UserWrite")]
    partial class AchievmentsTest_UserWrite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("User")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User.Domain.Entities.Achievment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2024, 10, 16, 17, 30, 58, 269, DateTimeKind.Utc).AddTicks(4799));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2024, 10, 16, 17, 30, 58, 269, DateTimeKind.Utc).AddTicks(5053));

                    b.HasKey("Id");

                    b.ToTable("Achievments", "User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14cfe78a-3794-4adf-b773-d70fc1491fdd"),
                            Description = "Выиграйте игру в роли президента",
                            Name = "Великий вождь"
                        },
                        new
                        {
                            Id = new Guid("9394332a-f4fe-4121-9909-a3c2a5761253"),
                            Description = "Произведите 5 ядерный бомб",
                            Name = "Давай нападай"
                        },
                        new
                        {
                            Id = new Guid("a20b2a5d-a2ac-45d7-a949-e148b3e37cda"),
                            Description = "Выиграйте, будучи обложенным санкциями всех стран",
                            Name = "Сильный и независимый"
                        });
                });

            modelBuilder.Entity("User.Domain.Entities.DomainUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2024, 10, 16, 17, 30, 58, 268, DateTimeKind.Utc).AddTicks(8503));

                    b.Property<string>("DefaultProfileImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2024, 10, 16, 17, 30, 58, 268, DateTimeKind.Utc).AddTicks(8789));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "User");
                });

            modelBuilder.Entity("User.Domain.Entities.Relationships.UserAchievment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AchievedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2024, 10, 16, 17, 30, 58, 270, DateTimeKind.Utc).AddTicks(5172));

                    b.HasKey("UserId", "AchievmentId");

                    b.HasIndex("AchievmentId");

                    b.ToTable("UserAchievments", "User");
                });

            modelBuilder.Entity("User.Domain.Entities.UserStatus", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("GameRole")
                        .HasColumnType("text");

                    b.Property<int?>("RoundNumber")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserStatuses", "User");
                });

            modelBuilder.Entity("User.Domain.Entities.Relationships.UserAchievment", b =>
                {
                    b.HasOne("User.Domain.Entities.Achievment", "Achievment")
                        .WithMany("UserAchievments")
                        .HasForeignKey("AchievmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User.Domain.Entities.DomainUser", "User")
                        .WithMany("UserAchievments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("User.Domain.Entities.UserStatus", b =>
                {
                    b.HasOne("User.Domain.Entities.DomainUser", "User")
                        .WithOne("UserStatus")
                        .HasForeignKey("User.Domain.Entities.UserStatus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User.Domain.Entities.Achievment", b =>
                {
                    b.Navigation("UserAchievments");
                });

            modelBuilder.Entity("User.Domain.Entities.DomainUser", b =>
                {
                    b.Navigation("UserAchievments");

                    b.Navigation("UserStatus")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
